apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
managedNodeGroups:
- name: m1
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true
  maxPodsPerNode: 110
  ssh: # enable SSH using SSM
    enableSsm: true